/* Generated by Together */

#include "CGPSSensor.h"
#include "CWaypoint.h"

#include<iostream>
using namespace std;

CGPSSensor::CGPSSensor(){
	//CGPSSensor class constructor
}

CWaypoint CGPSSensor::getCurrentPosition(){

	//curLatitude, CurLongitude - temporary variables to read in the current latitude and longitude values
	double curLatitude, curLongitude;

	//checkInput used to avoid longitude entry incase of wrong latitude entry
	int checkInput = 0;

	cout<<endl<<"GPS Sensor"<<endl;

	//read in latitude value from the user
	cout<<"  Enter latitude : ";
	cin>>curLatitude;


	//Checking if double value was entered for curLatitude
	if(cin.fail()||cin.get()!='\n')
	{
		//code execute if cin.fail() => non double value entered or
		//cin.get()!='\n' => characters or so at end of double value entry

		cin.clear();     //Clear cin flag
		checkInput=1;    //value modified
		cout<<endl<<"GPS Read Error !! Invalid latitude, Setting latitude and longitude to zero"<<endl;

		//setting latitude and longitude values to zero
		curLatitude=0;
		curLongitude=0;
	}

    //Prevent longitude entry incase of wrong latitude entry
	if (checkInput == 0)
	{
		//read in longitude value from the user
		cout << "  Enter longitude : ";
		cin >> curLongitude;

		//Checking if  double value was entered for curLongitude
		if(cin.fail()||cin.get()!='\n')
		{
			//code execute if cin.fail() => non double value entered or
			//cin.get()!='\n' => characters or so at end of double value entry

			cin.clear();   //Clear cin flag
			cout << endl<< "GPS Read Error !! Invalid longitude, Setting longitude and longitude to zero"<< endl;

			//setting latitude and longitude values to zero
			curLatitude = 0;
			curLongitude = 0;
		}
	}

	//Creating a CWaypoint object with user given lat long values
	CWaypoint currentPostion("Current Position",curLatitude,curLongitude);

	//returning currentPostion of type CWaypoint
	return(currentPostion);

}
