/* Generated by Together */

/**
 * @file name : CNavigationSystems.h *
 */

#ifndef CNAVIGATIONSYSTEMS_H
#define CNAVIGATIONSYSTEMS_H

#include "CGPSSensor.h"
#include "CRoute.h"
#include "CWaypoint.h"

using namespace std;
class CNavigationSystems {
public:

	/**
	 * CNavigationSystems constructor
	 */
    CNavigationSystems();

    /**
     * run - call all 3 private functions in this same class
     */
    void run();

private:

    /**
     * enterRoute- adds Waypoint and POIs to route
     */
    void enterRoute();

    /**
     * printRoute -print route details, number and list of Wypoints and POIs
     */
    void printRoute();

    /**
     * printDistanceCurPosNextPoi- gets current lat lon values and calculates distance to nearest POiI in route.
     */
    void printDistanceCurPosNextPoi();

private:
    CGPSSensor m_GPSSensor;
    CRoute m_route;
    CPoiDatabase m_PoiDatabase;
    CWpDatabase m_WpDatabase;
};

#endif //CNAVIGATIONSYSTEMS_H
